name: "Test Workflow"

on:
  workflow_dispatch:
  schedule: 
    - cron: "*/5 * * * *"

jobs:
  build:
    name: Build-test
    runs-on: ubuntu-latest

    steps:
      - name: Execute
        run: cd src && yarn && node index.js