name: "Test Workflow"

on:
  push: 
    branches:
      - master
  schedule: 
    - cron: "*/10 * * * *"

jobs:
  build:
    name: Build-test
    runs-on: ubuntu-latest

    steps:
      - name: Execute
        run: cd src .. && yarn && node index.js